language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_script:
  - cd source
  - npm install
  - npm install --global surge
  - npm install --global gulp-cli
script:
  - ../scripts/staging-build.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
    - ../scripts/staging-deploy.sh
branches:
  only:
    staging
